        tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "on-primary-fixed": "#001a41",
                        "surface-bright": "#f8f9fa",
                        "on-surface": "#191c1d",
                        "tertiary-fixed-dim": "#ffb3b2",
                        "surface-container-highest": "#e1e3e4",
                        "on-tertiary-fixed-variant": "#92001f",
                        "secondary-fixed": "#dde3eb",
                        "on-secondary-container": "#5f656c",
                        "surface": "#f8f9fa",
                        "on-secondary-fixed": "#161c22",
                        "outline-variant": "#c1c6d7",
                        "on-background": "#191c1d",
                        "secondary-container": "#dde3eb",
                        "on-error": "#ffffff",
                        "on-tertiary": "#ffffff",
                        "on-surface-variant": "#414754",
                        "primary-fixed": "#d8e2ff",
                        "secondary-fixed-dim": "#c1c7ce",
                        "surface-tint": "#005bc0",
                        "on-primary-container": "#fefcff",
                        "primary-container": "#0070ea",
                        "on-error-container": "#93000a",
                        "inverse-surface": "#2e3132",
                        "outline": "#717786",
                        "tertiary-fixed": "#ffdad9",
                        "tertiary": "#b6152e",
                        "on-primary-fixed-variant": "#004493",
                        "surface-dim": "#d9dadb",
                        "inverse-primary": "#adc7ff",
                        "on-primary": "#ffffff",
                        "surface-container": "#edeeef",
                        "surface-variant": "#e1e3e4",
                        "on-secondary-fixed-variant": "#41474e",
                        "surface-container-high": "#e7e8e9",
                        "on-tertiary-container": "#fffbff",
                        "primary-fixed-dim": "#adc7ff",
                        "error": "#ba1a1a",
                        "on-secondary": "#ffffff",
                        "primary": "#0059bb",
                        "background": "#f8f9fa",
                        "secondary": "#595f65",
                        "tertiary-container": "#d93343",
                        "surface-container-lowest": "#ffffff",
                        "error-container": "#ffdad6",
                        "on-tertiary-fixed": "#410008",
                        "surface-container-low": "#f3f4f5",
                        "inverse-on-surface": "#f0f1f2"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.125rem",
                        "lg": "0.25rem",
                        "xl": "0.5rem",
                        "full": "0.75rem"
                    },
                    "fontFamily": {
                        "headline": ["Inter"],
                        "body": ["Inter"],
                        "label": ["Inter"]
                    }
                },
            },
        }
