            <div id="view-analytics" class="view-content hidden">
                <header class="mb-12">
                    <h2 class="text-4xl font-black text-slate-900 dark:text-white mb-2">Analytics</h2>
                    <p class="text-slate-500">Visualizing your habit distribution and patterns.</p>
                </header>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div
                        class="bg-white dark:bg-slate-900 p-8 rounded-[2rem] shadow-sm border border-slate-100 dark:border-slate-800">
                        <h3 class="font-bold mb-6">Hourly Distribution</h3>
                        <div class="h-64 flex items-end gap-2 px-2" id="hourlyChart">
                            <!-- Bars generated by JS -->
                        </div>
                        <div class="flex justify-between text-[10px] text-slate-400 mt-4 px-2">
                            <span>00:00</span>
                            <span>12:00</span>
                            <span>23:00</span>
                        </div>
                    </div>
                    <div
                        class="bg-white dark:bg-slate-900 p-8 rounded-[2rem] shadow-sm border border-slate-100 dark:border-slate-800">
                        <h3 class="font-bold mb-6">Activity Frequency</h3>
                        <div class="space-y-4" id="frequencyList">
                            <!-- Top activities -->
                        </div>
                    </div>
                </div>
            </div>
